mysite/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls'))
]

polls/urls.py
from django.urls import path
from . import views


app_name = "polls"
urlpatterns = [
    path('',views.Index.as_view(),name="index"),
    path('create_question/',views.Question_create.as_view(),name='create'),
    path('<int:pk>/update_question/',views.Question_update.as_view(),name="update"),
    path('<int:pk>/question_delete',views.Question_delete.as_view(),name="delete"),
    path('login_form/',views.formview,name="login"),
    path('choice_form/',views.choice_form,name="choice"),
    path('<int:pk>/create_new_choice',views.create_new_choice,name="create_new_choice"),
    path('<int:pk>/detail/',views.Question_detail.as_view(),name="detail"),
    path("<int:pk>/results/",views.Result_detail.as_view(),name="results"),
    path('<int:question_id>/vote/',views.vote,name="vote")
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
import datetime
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse('polls:index')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey('Question',on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.forms import ValidationError
from django.core import validators
from .models import Question,Choice

def check_z(value):
    if value[0].lower() != 'z':
        raise ValidationError("Please make sure the name starts with a z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_z])
    email = forms.EmailField()
    vmail = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])

    # def clean_botcatcher(self):
    #     if len(self.cleaned_data['botcatcher']) > 0:
    #         raise ValidationError("Gotcher bot")

    def clean(self):
        all_cleaned_data = super().clean()
        email = all_cleaned_data['email']
        vmail = all_cleaned_data['vmail']

        if email != vmail:
            raise ValidationError("You emails did not match")
    
    
class Create_choice(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text',)

class Create_new_choice(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ('choice_text',)

polls/views.py
from django.shortcuts import render,get_object_or_404,get_list_or_404
from django.http import HttpResponse,Http404, HttpResponseRedirect
from .models import Question,Choice
from django.template import loader
from django.urls import reverse,reverse_lazy
from django.views.generic import TemplateView,DetailView,ListView,CreateView,UpdateView,DeleteView
from .forms import FormName,Create_choice,Create_new_choice
from django.shortcuts import get_object_or_404

# Create your views here.


def formview(request):
    form = FormName()

    if request.method == 'POST':
        form = FormName(request.POST)
        
        if form.is_valid():
            print(form.cleaned_data['name'])
            print(form.cleaned_data['email'])
            print(form.cleaned_data['text'])
            form = FormName()


    return render(request,'polls/login_form.html',{'form':form})

class Index(ListView):
    template_name = "polls/index.html"
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

    

class Question_detail(DetailView):
    template_name = 'polls/detail.html'
    model = Question

class Question_create(CreateView):
    model = Question
    fields = ['question_text']

class Question_update(UpdateView):
    model = Question
    fields = ['question_text']

class Question_delete(DeleteView):
    model = Question
    success_url = reverse_lazy('polls:index')



    

def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'polls/detail.html',{'question':question,'error_message':"Please select an option"})

    else:
        selected_choice.votes += 1
        selected_choice.save()
        
#HttpResponseRedirect takes a single argument mainly the reverse function which helps avoid hard coding URL
    return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

class Result_detail(DetailView):
    template_name = "polls/results.html"
    model = Question

def choice_form(request):
    choice = Create_choice()

    if request.method == "POST":
        choice = Create_choice(request.POST)

        if choice.is_valid():
            q=Question(question_text=choice.cleaned_data['question_text'])
            q.save()


    return render(request,'polls/choice_form.html',{'choice':choice})

def create_new_choice(request,pk):
    form = Create_new_choice()

    if request.method == "POST":
        form = Create_new_choice(request.POST)
        if form.is_valid():
            q = get_object_or_404(Question,pk=pk)
            print(q)
            q.choice_set.create(choice_text=form.cleaned_data['choice_text'],votes=0)
            q.save()

            return HttpResponseRedirect(reverse('polls:detail',args=(pk,)))

    return render(request,'polls/create_choice_form.html',{'form':form})

polls/templates/polls/choice_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Choice form</h1>
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ choice.as_p }}
            <input type="submit" value="submit">
        </form>
    </div>

</body>

</html>

polls/templates/polls/create_choice_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Creating Choice Form</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="create choice">
    </form>
    
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_id }}</h1>
            </legend>
            {% if error_message %}
            <p><strong class="warning">{{ error_message }}!</strong></p>
            {% endif %}

            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text}}</label><br>
            {% endfor %}
        </fieldset>
        <button><a href="{% url 'polls:update' question.pk %}">Update</a></button>
        <button><a href="{% url 'polls:delete' question.pk %}">Delete</a></button>
        <button><a href="{% url 'polls:create_new_choice' question.pk %}">Create new choice</a></button>
        <input type="submit" value="vote">
    </form>

</body>

</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>polls</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<body>
    <div class="p-5 rounded bg-light">
        <div class="container">
            <h1 class="display-4">Poll Question</h1>
            {% if latest_question_list %}
            <ol>
                {% for question in latest_question_list %}
                <li class="lead">{{ question }} <span><a href="{% url 'polls:detail' question.id %}">vote</a></span>
                </li>
                {% endfor %}
            </ol>
            {% else %}
            <p>No polls are available</p>
            {% endif%}
            <a href="{% url 'polls:create' %}">New Question</a>

        </div>

    </div>

</body>

</html>

polls/templates/polls/login_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>

</body>

</html>

polls/templates/polls/question_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Delete: {{ question.question_text }}</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger"><a href="{% url 'polls:detail' question.pk %}">cancel</a></button>
        <input type="submit" value="delete">
    </form>
    
</body>
</html>

polls/templates/polls/question_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% if not form.instance.pk %}
    <h1>Create Poll Question</h1>
    {% else %}
    <h1>Update Poll Question</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="create">Create</button>
    </form>


</body>

</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes}} vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>